boards:
  node_1:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM01-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.1_data_processing
  node_2:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM02-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.2_data_processing
  node_3:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM03-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.3_data_processing
  node_4:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM04-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.4_data_processing
  node_5:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM05-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.5_data_processing
  node_6:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM06-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.6_data_processing
  node_7:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM07-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.7_data_processing
  node_8:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM08-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.8_data_processing
  node_9:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM09-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.9_data_processing
  node_10:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM10-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.10_data_processing
  node_11:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.11_data_processing
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_609ee56fd469e91198ae6dd63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_12:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.12_data_processing
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_2634494dc969e911b0fd6ad63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_13:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.13_data_processing
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_6cf086e6c368e9119e476dd63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_14:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.14_data_processing
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_a8a1f6d9d669e9119d266fd63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_15:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.15_data_processing
    runtime_configuration:  
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_865b07a4c468e911b54f70d63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_16:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.16_data_processing
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_32975bc3d268e9119c546ad63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_17:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.17_data_processing
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_bc5513fbdf69e91190d2280c3da6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_18:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.18_data_processing
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_6448cac7cc68e911bae56dd63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_19:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.19_data_processing
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_ca84950ce269e9118e68300c3da6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_20:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_ROOT_DIR}}/sdkconfig
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/configurations/sdkconfig.overrides.20_data_processing
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_5697eeb2db68e911943c6fd63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_edge: # TODO(raphaelhetzel) move to Raspberry Pi
    type: "UNIX-CMAKE"
    runtime_configuration:
      binary_name: "uActorBin"
      parameters:
        - --node-id=node_edge
        - --server-node=node_cloud
        - --tcp-external-address=192.168.50.3
    build_configuration:
      root_directory: {{TESTBED_ROOT_DIR}}/posix_bin
      configuration_name: "default"
  #
  # node_cloud: #TODO(raphaelhetzel) update server to 20.04
  #   type: "UNIX-CMAKE"
  #   runtime_configuration:
  #     binary_name: "uActorBin"
  #     parameters:
  #       - --node-id=node_edge
  #       - --server-node=node_cloud
  #       - --tcp-listen-ip=0.0.0.0
  #     remote:
  #       host: "0.0.0.0"
  #       root_directory: "/home/raphael/uActorTest"
  #   build_configuration:
  #     root_directory: {{TESTBED_ROOT_DIR}}/posix_bin
  #     configuration_name: "default"
experiments:
  default:
    required_limit_count: 1
    limits:
      default:
        _reboot: 1
      node_1:
        done: 1
  leaf_run_1:
    hooks:
      _all:
       _ready: '/bin/bash $TESTBED_CONFIG_DIR/ready_hook.sh leaf'
  leaf_run_2:
    hooks:
      _all:
       _ready: '/bin/bash $TESTBED_CONFIG_DIR/ready_hook.sh leaf'
  leaf_run_3:
    hooks:
      _all:
       _ready: '/bin/bash $TESTBED_CONFIG_DIR/ready_hook.sh leaf'
  leaf_run_4:
    hooks:
      _all:
       _ready: '/bin/bash $TESTBED_CONFIG_DIR/ready_hook.sh leaf'
  edge_run_1:
    hooks:
      _all:
        _ready: '/bin/bash $TESTBED_CONFIG_DIR/ready_hook.sh edge'
  edge_run_2:
    hooks:
      _all:
        _ready: '/bin/bash $TESTBED_CONFIG_DIR/ready_hook.sh edge'
  edge_run_3:
    hooks:
      _all:
        _ready: '/bin/bash $TESTBED_CONFIG_DIR/ready_hook.sh edge'
  edge_run_4:
    hooks:
      _all:
        _ready: '/bin/bash $TESTBED_CONFIG_DIR/ready_hook.sh edge'
  cloud_run_1:
    hooks:
      _all:
        _ready: '/bin/bash $TESTBED_CONFIG_DIR/ready_hook.sh cloud'
  cloud_run_2:
    hooks:
      _all:
        _ready: '/bin/bash $TESTBED_CONFIG_DIR/ready_hook.sh cloud'
  cloud_run_3:
    hooks:
      _all:
        _ready: '/bin/bash $TESTBED_CONFIG_DIR/ready_hook.sh cloud'
  cloud_run_4:
    hooks:
      _all:
        _ready: '/bin/bash $TESTBED_CONFIG_DIR/ready_hook.sh cloud'