boards:
  node_1:
    type: "UNIX-GENERIC"
    runtime_configuration:
      binary_path: "/home/pi/uActorEVAL"
      parameters:
        - "--node-id=96A679"
        - "--tcp-external-address=192.168.50.231"
      remote:
        host: "cm-pi3"
        root_directory: "/home/pi/"
    build_configuration:
      configuration_name: "example"
  node_2:
    type: "UNIX-GENERIC"
    runtime_configuration:
      binary_path: "/home/pi/uActorEVAL"
      parameters:
        - "--node-id=979E51"
        - "--tcp-external-address=192.168.50.232"
      remote:
        host: "cm-pi4"
        root_directory: "/home/pi/"
    build_configuration:
      configuration_name: "example"
experiments:
  default:
    hooks:
       _all:
        _ready: '/bin/bash $TESTBED_ROOT_DIR/../evaluation/tools/per_node_ready_hook.sh evaluation_local_troughput.yml'
    limits:
      default:
        time_for_10000: 10
  run_1: {}
  run_2: {}
  run_3: {}
  run_4: {}
  run_5: {}
  run_6: {}
  run_7: {}
  run_8: {}
  run_9: {}
  run_10: {}