boards:
  node_1:
    type: "UNIX-GENERIC"
    runtime_configuration:
      binary_path: "/home/hetzel/uActorEVAL"
      parameters:
        - "--node-id=96A679"
        - "--tcp-external-address=1.2.3.4" # Public IP removed
      remote:
        host: "cm-optiplex"
        root_directory: "/home/hetzel/"
    build_configuration:
      configuration_name: "example"
experiments:
  default:
    hooks:
       _all:
        _ready: '/bin/bash $TESTBED_ROOT_DIR/../evaluation/tools/local_per_node_ready_hook.sh evaluation_local_troughput.yml'
    limits:
      default:
        time_for_10000: 25
  run_1: {}
  run_2: {}
  run_3: {}
  run_4: {}
  run_5: {}
  run_6: {}
  run_7: {}
  run_8: {}
  run_9: {}
  run_10: {}
  run_11: {}
  run_12: {}
  run_13: {}
  run_14: {}
  run_15: {}
  run_16: {}
  run_17: {}
  run_18: {}
  run_19: {}
  run_20: {}
