boards:
  node_1:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM01-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
  node_2:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM02-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
  node_3:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM03-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
  node_4:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM04-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
  node_5:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM05-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
  node_6:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM06-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
  node_7:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM07-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
  node_8:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM08-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
  node_9:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM09-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
  node_10:
    type: "ESP32-IDF"
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_TUM10-if00-port0"
      remote:
        host: "cm-pi1"
        root_directory: "/home/pi/remote_testbed"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
  node_11:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_609ee56fd469e91198ae6dd63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_12:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_2634494dc969e911b0fd6ad63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_13:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_6cf086e6c368e9119e476dd63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_14:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_a8a1f6d9d669e9119d266fd63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_15:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
    runtime_configuration:  
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_865b07a4c468e911b54f70d63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_16:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_32975bc3d268e9119c546ad63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_17:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_bc5513fbdf69e91190d2280c3da6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_18:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_6448cac7cc68e911bae56dd63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_19:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_ca84950ce269e9118e68300c3da6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
  node_20:
    type: "ESP32-IDF"
    build_configuration:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
    runtime_configuration:
      serial_device: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_5697eeb2db68e911943c6fd63ca6d3af-if00-port0"
      remote:
        host: "cm-pi2"
        root_directory: "/home/pi/remote_testbed"
experiments:
  default:
    hooks:
       _all:
        _ready: '/bin/bash $TESTBED_ROOT_DIR/../evaluation/tools/per_node_ready_hook.sh evaluation_local_troughput.yml'
    limits:
      default:
        time_for_10000: 10
  normal: {}
  hibernation:
    default_build_overrides:
      sdkconfig: {{TESTBED_CONFIG_DIR}}/../sdkconfig.microbenchmarks
      sdkconfig_overrides: {{TESTBED_CONFIG_DIR}}/sdkconfig.overrides.hibernation